---
# tasks file for roles/launch-app

- name: Launch app container
  docker_container:
    name: app
    image: tatsuwo/tp-devops:simple-http-server # Image Docker à utiliser pour le conteneur
    networks:
      - name: app-network
